### ISSUE TITLE
HDK 1.1 version, one file opens with errors in Creo

### ISSUE THREAD

**Issue by gurcankivci** [OSVR/OSVR-HDK#1]
When I tried to open EILEEN_HMD_ASM_GDC_0128.ASM, parts MODEL_HEAD_1.PRT and OLD-EILEEN-TOP_ASSY.ASM opens with error (marked red). After unzipping the same files over, error remained. Does this error persist for others?

**Comment by gurcankivci** [comment]
The file is still not okay, but it is not the important file. Use the .igs file in OSVR-HDK-master\HDK Ver 1.1\mechanical\HMD folder.

**Comment by MulanVR** [comment]
this distribution requires Creo 2.0 to open. Which version of Creo were you using?
