### ISSUE TITLE
Can't open brd files

### ISSUE THREAD

**Issue by jack-vrstudios** [OSVR/OSVR-HDK#3]
I am trying to use Eagle 7.4.0 Light Edition to open the brd files, but I get the "Start tag expected" error that usually means the file was generated with a different software.  What software did you use to generate the brd files?

**Comment by rpavlik** [comment]
It looks like they were made with Cadence Allegro - at least, I could get them to open with a reader for that. In any case, the main board is 12 layers, and IIRC the free version of Eagle limits you to 2 right? I'm not terribly well versed in the EDA software market or file formats, or whether there's a better interchange format to use.

I agree this should at least be documented better, it took me a bit of digging to figure out how to open the files.

**Comment by ohmahgawditbob** [comment]
Is there anything I can use to open/print for photoresist etching Cadence Allegro boards without paying insane amounts of money and without having to search for 5 years to find the download site?

**Comment by Kasijjuf** [comment]
Will KiCad work? http://kicad-pcb.org

**Comment by godbyk** [comment]
You should be able to view the files with the free [Cadence Allegro Viewer](https://www.cadence.com/content/cadence-www/global/en_US/home/tools/allegro-downloads-start.html).

**Comment by rpavlik** [comment]
FWIW, it's a 6-layer board, fabricating it yourself may be a bit beyond DIY photoresist etching. But yes, the only thing that opens it is the Cadence Allegro Viewer (unless you have another $$$ EDA tool that can import those files).

I think there are Gerber files in there for at least some of the revs, though, which are what you'd need for production.
