### ISSUE TITLE
Excel file for materials list won't open in excel.

### ISSUE THREAD

**Issue by KK4BitsPerSecond** [OSVR/OSVR-HDK#5]
HDMI_T30I_S2_BOM_final-0118.xlsx won't open. When I try to open it, excel just freezes.

**Comment by MulanVR** [comment]
I can open it with no problems from multiple PCs and OSes and also from my phone just now.
Which version of excel are you using?

**Comment by KK4BitsPerSecond** [comment]
MS Office 2013 is giving me fits. It opens just fine in Numbers, I just tried it on my phone. Weird.
