### ISSUE TITLE
No PDF schematics for HDK 1.3?

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-HDK#6]
There are fairly complete sets of PDF schematics for the 1.2, and a few for 1.4 (just the belt box and HMD mobo - missing the IR board at least), but just the brd (Allegro?) and gerber files for the 1.3.

**Comment by MulanVR** [comment]
1.3 and 1.4 units are sharing the same schematics. 
Let me know if this is ok to close.
