### ISSUE TITLE
IR board .brd file for HDK 1.3 does not appear to match shipped unit

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-HDK#7]
Using the Cadence free physical viewer, I looked at the IR Board .brd file for the 1.3, but it appears to be missing the protruding section with the P5 programming header found in my 1.3 unit, which I was told was a standard production unit.

![1 3 ir board](https://cloud.githubusercontent.com/assets/61129/16121697/dc191dc8-33a9-11e6-98fb-56740f086c2a.jpg)

Continuity tests indicate it has the same pinout as the unpopulated P3 programming header, but the connector is undocumented, etc.

**Comment by MulanVR** [comment]
Ryan, that's a 1.4 board. We gave you the newer board for testing in one of
our special prototypes for your contribution
The connector we changed based on ST link V2 programmer availability at
that time and the connector is documented in the mechanical file and in the
allegro library.
